### PR TITLE
feat: Extract git remote into its own option.

### PR DESCRIPTION
**Pull request by calavera**
This makes the usage of git remotes more explicit and easier to understand. It also allows to combine gitRemote and manifestPath if the manifest file is not in the root of the git repository.

/cc @brainstorm , @mmalenic

### CODE REVIEW

**Comment by brainstorm** [comment]
Kudos for those added changes, me and Marko had a few discussions about what to include in the first cut/MVP of this feature and we were a bit torn about i.e caching or naming it different/separate than manifestPath (manifestUrl?).

Your change set makes a ton of sense, thank you!

**Review by brainstorm — APPROVED** [review]

**Review by mmalenic — APPROVED** [review]
Awesome, thanks!

**Comment by calavera** [comment]
I just wish Projen and GitHub Actions didn't break this repository so often so contributing here could be more smooth. I'll release these changes as soon as I'm done fixing the release workflow 🤦

**Comment by calavera** [comment]
@brainstorm @mmalenic Release 0.0.31 should have these changes.

**Pull request merged**
